<a id="1"></a>
# <p style="background-color:#4E937A;font-family:Courier New;color:#EDEDED;font-size:100%;text-align:center;border-radius:15px 15px;">Data scrape from imDB movies web page</p>

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Initialize an empty list to store the scraped data
movies_list = []

# Start with the first page of the list
base_url = 'https://www.imdb.com/search/title?genres=drama&start=1&explore=title_type,genres&ref_=adv_nxt'

# Set the number of pages to scrape
num_pages = 100
counter = 0

for i in range(num_pages):
    # Send a GET request to the current page
    response = requests.get(base_url)
    
    # Parse the HTML content of the response
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # Scrape the data from the current page using BeautifulSoup methods
    movies = soup.find_all('div', class_='lister-item mode-advanced')
    for movie in movies:
        title = movie.h3.a.text
        year = movie.h3.find('span', class_='lister-item-year').text

        runtime = movie.find('span', class_='runtime')
        runtime_text = runtime.string if runtime is not None else 'Runtime not found.'

        genre = movie.find('span', class_='genre').text.strip()

        certificate = movie.find('span', class_='certificate')
        certificate_text = certificate.string if certificate is not None else 'Certificate not found.'

        rating = movie.find('div', class_='inline-block ratings-imdb-rating')
        rating_text = rating.text.strip() if rating is not None else 'Rating not found.'

        votes = movie.find('span', attrs={'name': 'nv'})
        votes_text = votes.string if votes is not None else 'Votes not found.'

        # Limit the number of printed values
        if counter < 20:
            print(f'Title: {title}')
            print(f'Year: {year}')
            print(f'Runtime: {runtime_text}')
            print(f'Genre: {genre}')
            print(f'Certificate: {certificate_text}')
            print(f'Rating: {rating_text}')
            print(f'Votes: {votes_text}')

        counter += 1

        # Append the scraped data to the movies_list
        movies_list.append({
            'Title': title, 
            'Year': year, 
            'Runtime': runtime_text,
            'Genre': genre, 
            'Certificate': certificate,
            'Rating': rating_text, 
            'Votes': votes_text
        })

    # Find the link to the next page
    next_page = soup.find('a', class_='lister-page-next next-page')['href']
    
    # Construct the URL of the next page
    base_url = 'https://www.imdb.com' + next_page

# Create a pandas DataFrame from the movies_list
movies_df = pd.DataFrame(movies_list)

# Print the first few rows of the DataFrame
display(movies_df.head(20))

Title: Nasljeđe
Year: (2018–2023)
Runtime: 60 min
Genre: Comedy, Drama
Certificate: Certificate not found.
Rating: 8.8
Votes: 184,147
Title: The Diplomat
Year: (II) (2023– )
Runtime: 50 min
Genre: Drama, Thriller
Certificate: Certificate not found.
Rating: 8.1
Votes: 24,615
Title: Citadel
Year: (2023– )
Runtime: Runtime not found.
Genre: Action, Drama, Thriller
Certificate: Certificate not found.
Rating: 6.3
Votes: 9,195
Title: Love & Death
Year: (2023)
Runtime: 57 min
Genre: Biography, Crime, Drama
Certificate: Certificate not found.
Rating: 7.6
Votes: 5,149
Title: Ted Lasso
Year: (2020– )
Runtime: 30 min
Genre: Comedy, Drama, Sport
Certificate: Certificate not found.
Rating: 8.8
Votes: 257,502
Title: Dune: Part Two
Year: (2023)
Runtime: Runtime not found.
Genre: Action, Adventure, Drama
Certificate: Certificate not found.
Rating: Rating not found.
Votes: Votes not found.
Title: Sweet Tooth: Rogati dječak
Year: (2021– )
Runtime: 50 min
Genre: Action, Adventure, Drama
Certificate: Certificate not found.
Rating: 7.8
Votes: 58,856
Title: Beef
Year: (2023– )
Runtime: 30 min
Genre: Comedy, Drama
Certificate: Certificate not found.
Rating: 8.2
Votes: 66,805
Title: The Hunger Games: The Ballad of Songbirds and Snakes
Year: (2023)
Runtime: Runtime not found.
Genre: Action, Adventure, Drama
Certificate: Certificate not found.
Rating: Rating not found.
Votes: Votes not found.
Title: Silo
Year: (2023– )
Runtime: Runtime not found.
Genre: Drama, Sci-Fi
Certificate: Certificate not found.
Rating: 8.3
Votes: 5,118
Title: Firefly Lane
Year: (2021–2023)
Runtime: Runtime not found.
Genre: Drama, Romance
Certificate: Certificate not found.
Rating: 7.5
Votes: 29,926
Title: Barry
Year: (2018–2023)
Runtime: 30 min
Genre: Action, Comedy, Crime
Certificate: Certificate not found.
Rating: 8.4
Votes: 94,033
Title: Queen Charlotte: A Bridgerton Story
Year: (2023)
Runtime: 60 min
Genre: Biography, Drama, History
Certificate: Certificate not found.
Rating: 7.3
Votes: 12,099
Title: The Night Agent
Year: (2023– )
Runtime: 45 min
Genre: Action, Drama, Thriller
Certificate: Certificate not found.
Rating: 7.5
Votes: 68,313
Title: Yellowjackets
Year: (2021– )
Runtime: 60 min
Genre: Drama, Horror, Mystery
Certificate: Certificate not found.
Rating: 7.9
Votes: 63,094
Title: Beau se boji
Year: (2023)
Runtime: 179 min
Genre: Comedy, Drama, Horror
Certificate: R
Rating: 7.2
Votes: 12,814
Title: Fatal Attraction
Year: (2023– )
Runtime: Runtime not found.
Genre: Drama, Thriller
Certificate: Certificate not found.
Rating: 6.0
Votes: 922
Title: The Marvelous Mrs. Maisel
Year: (2017–2023)
Runtime: 57 min
Genre: Comedy, Drama
Certificate: Certificate not found.
Rating: 8.7
Votes: 122,847
Title: From
Year: (2022– )
Runtime: 52 min
Genre: Drama, Horror, Mystery
Certificate: Certificate not found.
Rating: 7.7
Votes: 30,914
Title: Vodoinstalateri Bijele kuće
Year: (2023)
Runtime: Runtime not found.
Genre: Biography, Drama, History
Certificate: Certificate not found.
Rating: 6.7
Votes: 1,279

,Title,Year,Runtime,Genre,Certificate,Rating,Votes
0,Nasljeđe,(2018–2023),60 min,"Comedy, Drama",None,8.8,"184,147"
1,The Diplomat,(II) (2023– ),50 min,"Drama, Thriller",None,8.1,"24,615"
2,Citadel,(2023– ),Runtime not found.,"Action, Drama, Thriller",None,6.3,"9,195"
3,Love & Death,(2023),57 min,"Biography, Crime, Drama",None,7.6,"5,149"
4,Ted Lasso,(2020– ),30 min,"Comedy, Drama, Sport",None,8.8,"257,502"
5,Dune: Part Two,(2023),Runtime not found.,"Action, Adventure, Drama",None,Rating not found.,Votes not found.
6,Sweet Tooth: Rogati dječak,(2021– ),50 min,"Action, Adventure, Drama",None,7.8,"58,856"
7,Beef,(2023– ),30 min,"Comedy, Drama",None,8.2,"66,805"
8,The Hunger Games: The Ballad of Songbirds and ...,(2023),Runtime not found.,"Action, Adventure, Drama",None,Rating not found.,Votes not found.
9,Silo,(2023– ),Runtime not found.,"Drama, Sci-Fi",None,8.3,"5,118"
10,Firefly Lane,(2021–2023),Runtime not found.,"Drama, Romance",None,7.5,"29,926"
11,Barry,(2018–2023),30 min,"Action, Comedy, Crime",None,8.4,"94,033"
12,Queen Charlotte: A Bridgerton Story,(2023),60 min,"Biography, Drama, History",None,7.3,"12,099"
13,The Night Agent,(2023– ),45 min,"Action, Drama, Thriller",None,7.5,"68,313"
14,Yellowjackets,(2021– ),60 min,"Drama, Horror, Mystery",None,7.9,"63,094"
15,Beau se boji,(2023),179 min,"Comedy, Drama, Horror",[R],7.2,"12,814"
16,Fatal Attraction,(2023– ),Runtime not found.,"Drama, Thriller",None,6.0,922
17,The Marvelous Mrs. Maisel,(2017–2023),57 min,"Comedy, Drama",None,8.7,"122,847"
18,From,(2022– ),52 min,"Drama, Horror, Mystery",None,7.7,"30,914"
19,Vodoinstalateri Bijele kuće,(2023),Runtime not found.,"Biography, Drama, History",None,6.7,"1,279"

In [4]:
movies_df['Votes'] = movies_df['Votes'].str.replace(',', '')

In [5]:

# convert the data types of each column using the astype method
movies_df1 = movies_df.astype({
    'Title': 'string',
    'Year': 'string',
    'Runtime': 'string',
    'Genre': 'string',
    'Certificate': 'string',
    'Rating': 'float',
    'Votes': 'int32'
})

# verify the new data types of each column
print(movies_df1.dtypes)

Title           string
Year            string
Runtime         string
Genre           string
Certificate     string
Rating         float64
Votes            int32
dtype: object

In [6]:
movies_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        5000 non-null   string
 1   Year         5000 non-null   string
 2   Runtime      5000 non-null   string
 3   Genre        5000 non-null   string
 4   Certificate  2128 non-null   string
 5   Rating       5000 non-null   float64
 6   Votes        5000 non-null   int32
dtypes: float64(1), int32(1), string(5)
memory usage: 254.0 KB

In [7]:
display(movies_df1.head())

,Title,Year,Runtime,Genre,Certificate,Rating,Votes
0,The Last of Us,(2023– ),50 min,"Action, Adventure, Drama",<NA>,8.9,357455
1,Shadow and Bone,(2021– ),60 min,"Action, Adventure, Drama",<NA>,7.6,98568
2,Swarm,(2023– ),60 min,"Comedy, Drama, Thriller",<NA>,7.2,6526
3,Ted Lasso,(2020– ),30 min,"Comedy, Drama, Sport",<NA>,8.8,241913
4,The Night Agent,(2023– ),30 min,"Action, Drama, Thriller",<NA>,7.7,20312

<a id="1"></a>
# <p style="background-color:#4E937A;font-family:Courier New;color:#EDEDED;font-size:100%;text-align:center;border-radius:15px 15px;">Export to excel file</p>

In [73]:
movies_df.to_excel('data/Movies.xlsx', index=False)

<a id="1"></a>
# <p style="background-color:#4E937A;font-family:Courier New;color:#EDEDED;font-size:100%;text-align:center;border-radius:15px 15px;">Export to CSV file</p>

In [74]:
movies_df.to_csv('data/movies.csv', index=False)

In [38]:
movies_df1.to_csv('data/movies1.csv', index=False)

# <p style="background-color:#4E937A;font-family:Courier New;color:#EDEDED;font-size:100%;text-align:center;border-radius:15px 15px;">Loading into postgreSQL database</p>

In [39]:
from sqlalchemy import create_engine, text
import pandas as pd

# Connect to the PostgreSQL database
engine = create_engine('postgresql://sibinuser:sib123@localhost:5432/sibin')

# Define the table schema
table_schema = '''CREATE TABLE imdb_movies1 (
                    ID SERIAL PRIMARY KEY,
                    TITLE VARCHAR(255),
                    YEAR VARCHAR(50),
                    RUNTIME VARCHAR(10),
                    GENRE VARCHAR(255),
                    CERTIFICATE VARCHAR(10),
                    RATING FLOAT(2),
                    VOTES INTEGER
                 );'''

# Create the table in PostgreSQL
with engine.connect() as conn:
    conn.execute(text(table_schema))

# Load the DataFrame
df = pd.read_csv("data/movies1.csv")

# Save the DataFrame to PostgreSQL
df.to_sql('imdb_movies1', engine, index=False, if_exists='replace')

1000

<a id="1"></a>
# <p style="background-color:#4E937A;font-family:Courier New;color:#EDEDED;font-size:100%;text-align:center;border-radius:15px 15px;">Loading into Snowflake database</p>

In [ ]:
import pandas as pd
import snowflake.connector

# Connection parameters
params = {
  'user': 'sibinuser',
  'password': '7tcAU5jxFTLDdWT',
  'account': 'xu18157.eu-central-1',
  'warehouse': 'COMPUTE_WH',
  'database': 'imdb_movies',
  'schema': 'public'
}

# Create connection
conn = snowflake.connector.connect(**params)

cur = conn.cursor()

movies_df = pd.read_csv('data/movies.csv')

# Replace NaN values with None
movies_df = movies_df.where(pd.notnull(movies_df), None)

# Create the movies table
cur.execute("""
    CREATE OR REPLACE TABLE IMDB_MOVIES.PUBLIC.MOVIES (
    ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    TITLE VARCHAR(255),
    YEAR VARCHAR(50),
    RUNTIME VARCHAR(10),
    GENRE VARCHAR(255),
    CERTIFICATE VARCHAR(10),
    RATING FLOAT(2),
    VOTES INTEGER,
    PRIMARY KEY(ID)
);
""")

movies_df['Votes'] = movies_df['Votes'].str.replace(',', '')

print(movies_df)


for index, row in movies_df.iterrows():
    cur.execute(
        "INSERT INTO IMDB_MOVIES.PUBLIC.MOVIES (TITLE, YEAR, RUNTIME, GENRE, CERTIFICATE, RATING, VOTES) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s)",
        (row['Title'], row['Year'], row['Runtime'], row['Genre'], row['Certificate'], row['Rating'], row['Votes'])
    )

""" My snowflake trial ended, but later on I found that this method is more efficient than using iterrows() because it uses bulk data operations to transfer
 data between the DataFrame and Snowflake, resulting in better performance.

import pandas as pd
from snowflake.connector import connect
from snowflake.connector.pandas_tools import write_pandas

after the imports:

success, nchunks, nrows, _ = write_pandas(conn, data, table_name, index=False)

Note:

Code with iterrows() method was running for about 40 minutes for 5k rows. """

cur.close()
conn.close()

                       Title         Year  Runtime                     Genre  \
0             The Last of Us     (2023– )   50 min  Action, Adventure, Drama
1                        Kit       (2022)  117 min                     Drama
2                        You     (2018– )   45 min     Crime, Drama, Romance
3     Luther: The Fallen Sun       (2023)  129 min     Crime, Drama, Mystery
4      Daisy Jones & The Six       (2023)   49 min     Drama, Music, Romance
...                      ...          ...      ...                       ...
4995               Chemistry       (2011)   30 min      Comedy, Crime, Drama
4996        Dama iz dvorišta       (2015)  104 min  Biography, Comedy, Drama
4997                Somebody     (2022– )   48 min    Crime, Drama, Thriller
4998                Aquarius  (2015–2016)   42 min   Biography, Crime, Drama
4999             The Kingdom       (2007)  110 min   Action, Drama, Thriller

     Certificate  Rating   Votes
0             PG     8.9  333142
1              R     7.8  105040
2              R     7.7  268531
3              R     6.4   29361
4              R     7.9    7673
...          ...     ...     ...
4995           R     5.1     753
4996       PG-13     6.7   30196
4997       PG-13     5.9    1380
4998       PG-13     7.0   12641
4999           R     7.0  127370

[5000 rows x 7 columns]

In [12]:
print(movies_df1.head())

             Title      Year Runtime                     Genre Certificate  \
0   The Last of Us  (2023– )  50 min  Action, Adventure, Drama        <NA>
1  Shadow and Bone  (2021– )  60 min  Action, Adventure, Drama        <NA>
2            Swarm  (2023– )  60 min   Comedy, Drama, Thriller        <NA>
3        Ted Lasso  (2020– )  30 min      Comedy, Drama, Sport        <NA>
4  The Night Agent  (2023– )  30 min   Action, Drama, Thriller        <NA>

   Rating   Votes
0     8.9  357455
1     7.6   98568
2     7.2    6526
3     8.8  241913
4     7.7   20312

In [15]:
print(movies_df.columns)

Index(['Title', 'Year', 'Runtime', 'Genre', 'Certificate', 'Rating', 'Votes'], dtype='object')

In [ ]:
# Still airing feature: Prints the movies and tv-shows from dataframe that are still airing.

still_airing = movies_df1[movies_df1['Year'].str.endswith('– )')]
print(still_airing)

                Title      Year  Runtime                      Genre  \
0      The Last of Us  (2023– )   50 min   Action, Adventure, Drama
1     Shadow and Bone  (2021– )   60 min   Action, Adventure, Drama
2               Swarm  (2023– )   60 min    Comedy, Drama, Thriller
3           Ted Lasso  (2020– )   30 min       Comedy, Drama, Sport
4     The Night Agent  (2023– )   30 min    Action, Drama, Thriller
...               ...       ...      ...                        ...
4949          Mammals  (2022– )   30 min              Comedy, Drama
4954         The Game  (2021– )   30 min     Comedy, Drama, Romance
4960         Leonardo  (2021– )  409 min  Biography, Drama, History
4995     Hockeyvaders  (2023– )   85 min              Comedy, Drama
4999           Maxine  (2022– )  180 min               Crime, Drama

     Certificate  Rating   Votes
0           <NA>     8.9  357455
1           <NA>     7.6   98568
2           <NA>     7.2    6526
3           <NA>     8.8  241913
4           <NA>     7.7   20312
...          ...     ...     ...
4949        <NA>     5.8    3320
4954        <NA>     6.2     631
4960        <NA>     7.2    3742
4995        <NA>     6.8      50
4999        <NA>     6.8     660

[547 rows x 7 columns]